modules:
  computational_setup:
    type: ComputationalSetup
    global_sync: false
    retry_time_seconds: 600
    random_seed: 4711
  vehicles:
    type: Vehicles
    path: berlin-v6.4-vehicleTypes.xml
  controller:
    type: Controller
    first_iteration: 0
    last_iteration: 0
    compression_type: Zst
  population:
    type: Population
    path: berlin-v6.4-0.1pct.plans-filtered.xml.gz
  output:
    type: Output
    overwrite_files: OverwriteExistingFiles
    profiling: !CSV
      level: INFO
    logging: Info
    write_events: File
    output_dir: output
  transit:
    type: Transit
    schedule_path: berlin-v6.4-transitSchedule.xml.gz
  qsim:
    type: QSim
    start_time: 0
    end_time: 129600
    ticks_per_second: 1
    sample_size: 0.001
    stuck_threshold: 30
    main_modes:
      - car
      - freight
      - truck
  network:
    type: Network
    path: berlin-v6.4-network-with-pt.xml.gz
  partitioning:
    type: Partitioning
    num_parts: 1
    method: !Metis
      vertex_weight:
        - InLinkCount
      edge_weight: Capacity
      imbalance_factor: 1.1
      iteration_number: 100
      contiguous: false
