modules:
  protofiles:
    type: ProtoFiles
    ids: "output/equil.ids.binpb"
    network: "output/equil.network.binpb"
    population: "output/equil.plans.binpb"
    vehicles: "output/equil.vehicles.binpb"
  partitioning:
    type: Partitioning
    num_parts: 12
    method: !Metis
  output:
    type: Output
    output_dir: ./assets/equil/output
    write_events: Proto
  routing:
    type: Routing
    mode: UsePlans
  simulation:
    type: Simulation
    start_time: 0
    end_time: 86400
    sample_size: 1.0
    stuck_threshold: 1000
    main_modes: ["car"]